---
- hosts: all
  tasks:
    - debug: var=hostvars

- hosts: living-room
  pre_tasks:
    - apt:
        name: apt-transport-https
        state: latest
      become: true
    - apt:
        update_cache: true
      become: true
  roles:
    - role: owncloud
      become: true
    - role: pihole
      become: true
    - role: firefly
      become: true

- hosts: devbox
  pre_tasks:
    - apt:
        name: apt-transport-https
        state: latest
        update_cache: true
      become: true
  roles:
    - role: owncloud
      become: true
    - role: pihole
      become: true
    - role: firefly
      become: true
