---
- name: Install docker container
  docker_container:
    name: mariadb
    image: mariadb/server
    recreate: yes
    cleanup: yes
    pull: yes
    restart: yes
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_password }}"
