---
- name: Install docker container
  docker_container:
    name: mysql
    image: mysql:latest
    recreate: yes
    auto_remove: yes
    cleanup: yes
    pull: yes
    restart: yes
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_password }}"
