---
- name: Install docker container
  environment:
    MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
    MYSQL_DATABASE: "{{ mysql_database }}"
    MYSQL_USER: "{{ mysql_user }}"
    MYSQL_PASSWORD: "{{ mysql_password }}"
  docker_container:
    name: mysql
    recreate: yes
    image: mysql:latest
    auto_remove: yes
    cleanup: yes
    pull: yes
    restart: yes
