---
- name: Install pip package
  apt:
    name: "python-pip"
    state: latest

- name: Install pip packages
  pip:
    name: "{{ item }}"
  with_items:
    - docker
    - docker-py
    - docker-compose

- name: add docker repo key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: add docker repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
    state: present

- name: Install docker package
  apt:
    name: "docker-ce"
    state: latest
    update_cache: true
