---
- name: Install pip package
  apt:
    name: "python-pip"
    state: latest

- name: Install pip packages
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker
    - docker-py

- name: Install docker compose
  pip:
    name: docker-compose
    state: present
    version: 18.06

- name: add docker repo key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add docker repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
    state: present

- name: Install docker package
  apt:
    name: "docker-ce"
    state: latest
    update_cache: true
