---
- name: fetch docker installation file
  get_url:
    url: https://get.docker.com
    dest: /home/pi/docker-setup.sh

- name: setup docker
  shell: sh /home/pi/docker-setup.sh

- name: ensure docker is enabled
  systemd:
    name: docker
    enabled: true
  notify:
    - restart docker
