---
- name: create tmp owncloud
  file:
    path: /tmp/owncloud
    state: directory

- name: fetch docker compose file
  get_url:
    url: https://ssi.le-piolot.fr/share/docker-compose/owncloud/docker-compose.yml
    dest: /tmp/owncloud/docker-compose.yml

- name: setup owncloud
  environment:
    OWNCLOUD_VERSION: latest
    OWNCLOUD_DOMAIN: "{{ owncloud_host }}"
    HTTP_PORT: "{{ owncloud_port }}"
    ADMIN_USERNAME: "{{ owncloud_user }}"
    ADMIN_PASSWORD: "{{ owncloud_password }}"
  docker_service:
    project_src: /tmp/owncloud

- name: upgrade owncloud
  environment:
    OWNCLOUD_VERSION: latest
    OWNCLOUD_DOMAIN: "{{ owncloud_host }}"
    HTTP_PORT: "{{ owncloud_port }}"
    ADMIN_USERNAME: "{{ owncloud_user }}"
    ADMIN_PASSWORD: "{{ owncloud_password }}"
  docker_service:
    project_src: /tmp/owncloud
    pull: yes
    remove_orphans: yes
    restarted: yes
  register: owncloud_output

- debug:
    var: owncloud_output
