---
- name: Install docker container
  docker_container:
    name: owncloud
    recreate: yes
    image: owncloud/server
    auto_remove: yes
    cleanup: yes
    pull: yes
    restart: yes
    env:
      OWNCLOUD_VERSION: latest
      OWNCLOUD_DOMAIN: "{{ owncloud_host }}"
      HTTP_PORT: "{{ owncloud_port }}"
      ADMIN_USERNAME: "{{ owncloud_user }}"
      ADMIN_PASSWORD: "{{ owncloud_password }}"
      OWNCLOUD_DB_USER: "{{ owncloud_database_user }}"
      OWNCLOUD_DB_PASSWORD: "{{ owncloud_database_password }}"
      OWNCLOUD_DB_NAME: "mysql-01:3306"
