---
- name: create tmp owncloud
  file:
    path: /tmp/owncloud
    state: directory

- name: fetch docker compose file
  get_url:
    url: https://raw.githubusercontent.com/owncloud-docker/server/master/docker-compose.yml
    dest: /tmp/owncloud/docker-compose.yml

- name: setup owncloud
  environment:
    OWNCLOUD_VERSION: latest
    OWNCLOUD_DOMAIN: "{{ owncloud_host }}"
    ADMIN_USERNAME: "{{ owncloud_user }}"
    ADMIN_PASSWORD: "{{ owncloud_password }}"
  docker_service:
    project_src: /tmp/owncloud

- name: upgrade owncloud
  command: docker-compose run --rm owncloud owncloud upgrade --noinput
  args:
    chdir: /tmp/owncloud
